# .github/workflows/ci.yml
name: ci
on:
  pull_request:
    branches: [ main ]   # run on PRs into main
  workflow_dispatch:      # allow manual runs from the Actions tab
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: env/requirements.txt

      - run: pip install -r env/requirements.txt

      - uses: quarto-dev/quarto-actions/setup@v2
        # installs Quarto CLI for the runner

      - name: Render essay
        run: quarto render essay.qmd

      - name: Upload site artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site/
